Kits:
  Bombtastic:
    Description: 'Don''t you just hate creepers? The way they creep up, hiss and explode! Well its time to take your revenge! Rip their guts out on death! Bombtastic gives you 1/3 chance of the creeper dropping tnt. Its time, to take revenge!'
    Free: true
    Price: 0
    Icon: TNT 0 1
    Ability:
      - Bombtastic
  Bourne:
    Description: 'This kit scrambles enemy players compasses when they get within 25 blocks of Jason Bourne'
    Free: true
    Price: 0
    Icon: COMPASS 0 1
    Ability:
      - Bourne
  Creeper:
    Description: 'Explode with the majestic power of a creeper upon death! Wreck havoc upon thy enemies for daring to kill one as powerful as you! Ruin their day as you destroy any hope and chance they had of winning! However! Theres a chance you will barely explode. Because as we all know. Humans were never meant to explode'
    Free: true
    Price: 0
    Icon: SULPHUR 0 1
    Ability:
      - Creeper
  Ghost:
    Description: 'When the game starts you are invisible until invincibility runs out!'
    Free: true
    Price: 0
    Icon: POTION 16398 1
    Ability:
      - PotionLover
  Herobrine:
    Description: 'Use your nether star to make a quick escape! Play a scary noise and sprint away, but there is a weakness effect for the distance you ran.. This only works against players with better armor then you however!'
    Free: true
    Price: 0
    Icon: NETHER_STAR 0 1
    Items:
      - NETHER_STAR 0 1 Unlootable 1 Name=Herobrines_Escape
    Ability:
      - Herobrine
  Miser:
    Description: 'Sick of people killing you and grabbing your hard earned loot? Worry no more! Revenge from the grave! They ain''t getting any of your loot! You no longer drop your items on death!'
    Free: true
    Price: 0
    Icon: CHEST 0 1
    Ability:
      - Miser
  Ninja:
    Description: 'Players with this kit have a Speed II buff during the day and a Jump II buff at night.'
    Free: true
    Price: 0
    Icon: REDSTONE_WIRE 0 1
    Ability:
      - Ninja
  Pussy:
    Description: 'Ever get accused of being a pussy? Now you can rub it in! Turn into a kitty cat after 10 seconds of sprinting! Wonderful if you want to become hard to see while you are doing your trademark pussying!'
    Free: true
    Price: 0
    Icon: POTION 16418 1
    Ability:
      - Pussy